import "@/styles/reset.css"
import "@/styles/variables.css"
import "@/styles/global.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className="layout">
        <div aria-hidden="true" className="overlay" />
        {children}
      </body>
    </html>
  )
}
